### ISSUE TITLE
Multiple Issues | Envoys 5.1.3

### ISSUE THREAD

**Issue by B-Knight49** [rxdn/Envoys#2]
Envoys 5.1.3 (Latest)
Paper Build #103
Minecraft 1.15.2
Image: [Plugins List](https://user-images.githubusercontent.com/26165117/75906262-537e7080-5e3e-11ea-8fcd-79115cc6761a.png)
Gist: [Envoys Config](https://gist.github.com/B-Knight49/3b15c426b10b041b82580dcd4beee3df)
Gist: [Latest.log](https://gist.github.com/B-Knight49/1dd9102e85d2fa613a241712efd33886)
Image: [Proof of purchase](https://user-images.githubusercontent.com/26165117/75908757-a9edae00-5e42-11ea-870d-7f1ca17ec2ec.png)

- [ ] Particles are broken. Enabled in settings, chests don't display any particles at all. See config.yml
- [x] Commands don't provide any feedback to chat/player
  - [x] /envoys list - when none are available
  - [x] /envoys clear - when none are cleared
  - [x] /envoys stop - when none to stop
- [x] /envoys reload does nothing. I'm forced to reload the entire plugin using a plugin manager
- [x] Calling in an envoy using a flare spawns it at 255 and tries to drop it even if `drop-from-sky` is set to false
- [x] `armor-stands-tick: false` in Paper.yml stops armour stands from having gravity. No, setting it to true is not a valid fix @.ryan on Discord. 
- [x] /envoys debug does nothing. It throws a ProtocolException:
`[18:48:19 WARN]: An error occurred:
[18:48:19 WARN]: java.net.ProtocolException: cannot write to a URLConnection if doOutput=false - call setDoOutput(true)`
- [x] There's no tab completion at all. [All commands are in red when being typed.](https://user-images.githubusercontent.com/26165117/75907717-b1ac5300-5e40-11ea-8e33-acb8dbc93603.png) This is after a full server restart too. 
 - [x] Code is obfuscated. Really? Are you serious. You don't do that for these exact reasons! I could've fixed all these myself if the code were not obfuscated. And yes, that's allowed by the license you use for the plugin:

> 1. PERMISSIONS
> This license allows the end user to use features of this plugin commercially **and to modify it for private use.**

I paid 4 quid for this. The issues I've outlined above are fairly reasonable things to expect to work for a premium plugin. What's really ticked me off, though, is the fact that the code is obfuscated and I can't even fix this myself. Were the code not obfuscated, I'd accept and endure this because I know plugins shouldn't be expected to be bug free. You've got DRM (it kindly spams the console on startup), you don't need complete jar obfuscation either. Obfuscate the class with the DRM, not everything so that people like myself can actually fix these things or maybe even help you by creating PR's. \rant

**Comment by Dot-Rar** [comment]
Sorry for the delay in response, I don't check GitHub issues too often. Anyhow;
> Particles are broken. Enabled in settings, chests don't display any particles at all. See config.yml

Just to ensure we're on the same page - you're aware that the particles spawn on envoy open, not constantly, correct?

> Commands don't provide any feedback to chat/player

Will add an additional message for these specific cases in the next update - I've been meaning to do it for a while but putting it off due to it being a low importance QOL thing

>  /envoys reload does nothing. I'm forced to reload the entire plugin using a plugin manager
Does the command have an output? Is anything printed in console? Is it just certain values that aren't reloaded? I need more details.

> Calling in an envoy using a flare spawns it at 255 and tries to drop it even if drop-from-sky is set to false

Could you clarify for me whether these are random location, pre-defined location (/envoy create), or flare envoys please?

> `armor-stands-tick: false in Paper.yml stops armour stands from having gravity. No, setting it to true is not a valid fix @.ryan on Discord

I'm not sure what you want me to do. I already explained to you that you either need to disable the drop from sky feature, or enable armour stand gravity - those are the only 2 options you have. When implementing this feature, I originally tried falling blocks but quickly ran into limitations with them meaning that I was forced to use armour stands. Since you clearly know your way around Spigot, if you think you know of a solution, I'd be more than happy to implement it.

> /envoys debug does nothing. It throws a ProtocolException:
[18:48:19 WARN]: An error occurred: [18:48:19 WARN]: java.net.ProtocolException: cannot write to a URLConnection if doOutput=false - call setDoOutput(true)

I'm pretty sure I fixed this for 5.1.3, however, I might've fixed it at a later point and not published it since it's not worth pushing on its own - if this is the case, it'll be fixed with the next release.

> There's no tab completion at all. All commands are in red when being typed. This is after a full server restart too.

Brigadier support will be coming at some point - just considering the best way to handle it with my command library since I built it before brigadier was even conceptualised

> Code is obfuscated. Really? Are you serious. You don't do that for these exact reasons! I could've fixed all these myself if the code were not obfuscated. And yes, that's allowed by the license you use for the plugin:
PERMISSIONS
This license allows the end user to use features of this plugin commercially and to modify it for private use.
I paid 4 quid for this. The issues I've outlined above are fairly reasonable things to expect to work for a premium plugin. What's really ticked me off, though, is the fact that the code is obfuscated and I can't even fix this myself. Were the code not obfuscated, I'd accept and endure this because I know plugins shouldn't be expected to be bug free. You've got DRM (it kindly spams the console on startup), you don't need complete jar obfuscation either. Obfuscate the class with the DRM, not everything so that people like myself can actually fix these things or maybe even help you by creating PR's. \rant

I understand your pain - I make sure to opensource all my freeware & freemium services that I operate, however, my plugin has been targeted specifically by leaking sites, so it is unfortunately required that I obfuscate the entire plugin to make tampering with it as difficult as possible for the leakers. Lots of different kinds of DRM as possible is the way to go if you want to stop them. Whilst you may disagree with this, and let me put it straight - I don't _like_ doing it either - if I had made this a free resource, it would be no where near the form it is in today, getting very rare updates.

To show that DRM is needed, I've attached an image of my sales graph, the month where a certain leak site removed my DRM is circled, and you can see the massive impact it has on sales.
![image](https://user-images.githubusercontent.com/29165304/76560766-cd93a280-6499-11ea-9669-21db95af6296.png)

It's unfortunate that it has to come to this, but my updated DRM has made the leakers give up on trying to crack my plugin (for now at least)

**Comment by B-Knight49** [comment]
> Just to ensure we're on the same page - you're aware that the particles spawn on envoy open, not constantly, correct?

Correct. There's no particles for us. Whilst on the topic though, particles located around the envoy prior to opening would be a neat feature too - if you're taking requests. 

> Will add an additional message for these specific cases in the next update - I've been meaning to do it for a while but putting it off due to it being a low importance QOL thing

Thanks. Saw you recently updated it. Will download soon.

> Does the command have an output? Is anything printed in console? Is it just certain values that aren't reloaded? I need more details.

"Reloaded successfully" is all I get in chat but nothing updates in game. It could be that it _is working_ just I don't know what exactly it is refreshing. From my testing, no changes to the configs were updated whatsoever and envoys were unchanged (names, rewards, other actions, etc).

> Could you clarify for me whether these are random location, pre-defined location (/envoy create), or flare envoys please?

Flare. Redstone torch placed on the ground.

> I'm not sure what you want me to do. I already explained to you that you either need to disable the drop from sky feature, or enable armour stand gravity - those are the only 2 options you have. When implementing this feature, I originally tried falling blocks but quickly ran into limitations with them meaning that I was forced to use armour stands. Since you clearly know your way around Spigot, if you think you know of a solution, I'd be more than happy to implement it.

You could easily still use armour stands, just change their location every X ticks. For example: 
- First off check if they're actually not falling / if the server is on Paper and has armor-stand-tick: false
- If above is true and fall-from-sky is true, use an alternative method for falling. Much more customisable too...
    - Every X amount of ticks (depending on how fast you want it to fall), have the Y-coordinate decrease by 1 until [Entity.IsOnGround](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Entity.html#isOnGround--). You can make it seem like it's using a parachute this way too since you can decide the rate of decent yourself.
    - If you wanna get really creative, you could even implement particle effects that float up from the chest as it's falling kinda like a smoke-grenade or flare. As it falls, the particles rise and it's visible - just an extra little feature to look nice
    - If you wanna be even more creative, you could probably make a crude-looking parachute from other entities or particle effects in-game. Some more invisible armour stands with wool for their heads or chickens attached to leads coming off of the chest, etc.  

> I'm pretty sure I fixed this for 5.1.3, however, I might've fixed it at a later point and not published it since it's not worth pushing on its own - if this is the case, it'll be fixed with the next release.

Thanks, I'll check it soon.

> Brigadier support will be coming at some point - just considering the best way to handle it with my command library since I built it before brigadier was even conceptualised

Alright, though I'm a little confused on why it's still red since the commands should be registered regardless. Nonetheless, you know best and aim to fix it so I can't complain.

> I understand your pain - I make sure to opensource all my freeware & freemium services that I operate, however, my plugin has been targeted specifically by leaking sites, so it is unfortunately required that I obfuscate the entire plugin to make tampering with it as difficult as possible for the leakers. Lots of different kinds of DRM as possible is the way to go if you want to stop them. Whilst you may disagree with this, and let me put it straight - I don't like doing it either - if I had made this a free resource, it would be no where near the form it is in today, getting very rare updates.

With all due respect dude, it's a waste of time. Crackers will get through it eventually regardless of the amount of layers you add to it. If people truly wanted to, they could simply upload your plugin as is but configure their network to block the outgoing connections you make or rather use a MITM attack to simply return whatever values it is expecting. 

Hell, during my testing from when I wrote this originally, I even copied the plugin we'd bought from you, off of our server (hosted in Germany, on a private server with a Minecraft hosting company) onto my _personal PC_, booted up a test server and it worked absolutely fine. There is absolutely nothing identical about the server we run and my PC and it had no issue starting up regardless. Though, if that wasn't the case, the plugin manager I use intercepts HTTP calls in the main thread and can either interrupt or provide information on the sites accessed. I didn't have the "interrupt mode" enabled, just the "notify" one and can already see every URL you use to protect your plugin. It'd take me no more than an hour or two, using that information, to have it running on any server I wanted... Ironically I didn't even need to do that!

Along with the recent changes to SpigotMC's rules too, severe obfuscation is truly a waste mate. You can't even obfuscate it enough anymore without pissing off the staff and risk getting your entire plugin pulled. And their new rules specifically state that you've gotta only obfuscate necessary areas rather than layers and layers of it thrown on every single one of your classes. You're fighting an uphill battle. The best remedy for piracy is offering a good, high quality plugin with lots of features, a nice finish to it and - I shit you not - a free version with less features and maybe even locked behind a "compile-wall", where you don't offer any binaries and demand the user to compile it for themselves. That'll weed out the noobies who just pirate things with no Java knowledge and it'll stop the actual crackers and Java experts from wasting their time because why would they upload something that's open-source to a leaking site? mcMMO is a **PERFECT** example of this. 

On another note, apologies for the pissed tone I took originally. It's frustrating when you pay actual money for something and it's so locked down that, even if you wanted to, you couldn't improve or amend it for your requirements. I think as well, understandably, you thought I might've been just another cry-baby noob who hasn't a clue about programming when we spoke on Discord. I felt like you were a little dismissive and that definitely didn't help when it came to setting the plugin up - which I did manage fine and it has admittedly been serving us well ever since so thanks nonetheless. I'll download the new updates soon and get back to you with things.

**Comment by Dot-Rar** [comment]
Will investigate the other issues tomorrow / Sunday, but I'll respond to the last part now:

>With all due respect dude, it's a waste of time. Crackers will get through it eventually regardless of the amount of layers you add to it. If people truly wanted to, they could simply upload your plugin as is but configure their network to block the outgoing connections you make or rather use a MITM attack to simply return whatever values it is expecting.

Whilst this is possible for those running VPSs or dedicated servers, this isn't a solution for those running on shared hosts, which I've seen most people who attempt to run cracked versions are. Those with dedicated servers or VPSs are more likely to have the financial ability to purchase a £4 plugin also, so I'm not terribly worried about this.

> Hell, during my testing from when I wrote this originally, I even copied the plugin we'd bought from you, off of our server (hosted in Germany, on a private server with a Minecraft hosting company) onto my personal PC, booted up a test server and it worked absolutely fine. There is absolutely nothing identical about the server we run and my PC and it had no issue starting up regardless. Though, if that wasn't the case, the plugin manager I use intercepts HTTP calls in the main thread and can either interrupt or provide information on the sites accessed. I didn't have the "interrupt mode" enabled, just the "notify" one and can already see every URL you use to protect your plugin. It'd take me no more than an hour or two, using that information, to have it running on any server I wanted... Ironically I didn't even need to do that!

This would require the user to install additional proprietary software from leak sites, which isn't the best idea, considering half of the stuff on leak sites is full of malware. Anyhow, I _do_ have a solution to this, which I would implement if someone were to do this. Can't share for obvious reasons.


> Along with the recent changes to SpigotMC's rules too, severe obfuscation is truly a waste mate. You can't even obfuscate it enough anymore without pissing off the staff and risk getting your entire plugin pulled.

I don't use severe obfuscation: I only use ProGuard. However, if I wished too, I would be allowed to use even Stringer or Zelix KlassMaster, as detailed [here](https://www.spigotmc.org/threads/approved-obfuscators.420746/)

> And their new rules specifically state that you've gotta only obfuscate necessary areas rather than layers and layers of it thrown on every single one of your classes

Could you point me to where the guidelines state this?

> You're fighting an uphill battle. The best remedy for piracy is offering a good, high quality plugin with lots of features, a nice finish to it and - I shit you not - a free version with less features and maybe even locked behind a "compile-wall", where you don't offer any binaries and demand the user to compile it for themselves. That'll weed out the noobies who just pirate things with no Java knowledge and it'll stop the actual crackers and Java experts from wasting their time because why would they upload something that's open-source to a leaking site? mcMMO is a PERFECT example of this.

This may be a solution for the big plugins like FactionsUUID that get hundreds of purchases every month, however, I'm relying on a relatively small amount (~15) of purchases every month to pay my server bills.

This is something I've done a lot of research on with many people, and invested a lot of time into. Sorry, but I'm not willing to compromise on this. I've seen before the effects of allowing the leakers to publish the plugin for free, which caused a sizeable hole in my wallet, which isn't exactly ideal for a 17 year old in full-time education without a job needing to pay bills.
